### ISSUE TITLE
Tried to build app and start it on emulator but with no success.

### ISSUE THREAD

**Issue by megarocks** [Abolitionist-Project/QuantiModo-Ionic-Template-App#30]
Did:
`ionic platform add ios`
`ionic build ios`
`ionic emulate ios`
Seems like no errors but emulator starts empty (blank white screen).

After that tried to do `gulp make` but it gives:
```
/Users/alt/sites/QuantiModo-Ionic-Template-App/node_modules/node-sass/lib/index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
    ^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/alt/sites/QuantiModo-Ionic-Template-App/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/alt/sites/QuantiModo-Ionic-Template-App/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/alt/sites/QuantiModo-Ionic-Template-App/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:435:26)
```
then tried to do: `npm install` - it gives errors because of access. Runned it with `sudo`
`sudo npm install` - it work ok but `gulp make` still gives an error. 
did `npm install node-sass` - this works without error, but 
`gulp make` still doesn't work

**Comment by mikepsinn** [comment]
@megarocks Did you already try `npm install node-sass`?
